name: Build daily plot

on:
  schedule:
    # Runs every day at 11:00 UTC (07:00 America/New_York during EDT; adjust as you like)
    - cron: "0 11 * * *"
  workflow_dispatch: {}  # allow manual run

permissions:
  contents: write  # needed to push docs/ updates back to the repo

concurrency:
  group: daily-plot
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # if you have a requirements.txt, use: pip install -r requirements.txt
          pip install yfinance pandas numpy matplotlib

      - name: Run script
        run: |
          # replace with your actual script filename if needed
          python auto_macro_pair_monitor.py

      - name: Commit & push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/ || true
          if ! git diff --cached --quiet; then
            git commit -m "Daily update: plots [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
